Add bookings
grigory-pc/java-shareit pull request #2
Opened 2022-08-22 20:21 UTC by grigory-pc

2022-08-23 17:50 UTC, ddddemo1984 requested changes

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private Validation validation;
Часть бинов инжектится через конструктор, часть через @Autowired, лучше сделать единообразно. Рекомендую везде написать private final и поставить аннотацию над классом @RequiredArgsConstructor

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Для консистентного состояния БД лучше использовать аннотацию Transactional. Причём здесь поставить @Transactional(readOnly = true), а над классами/методами меняющими данные @Transactional

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Задание "Бронирования должны возвращаться отсортированными по дате от более новых к более старым". Кроме ALL у тебя сортировка от более поздних к ранним(по возрастанию)

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/resources/schema.sql
> +);
Почему имена таблиц и полей в кавычках?

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    void deleteBooking(long userId, long bookingId);
Не используется

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingOutDto> getBookings(long userId);
Не используется

2022-08-23 17:50 UTC, ddddemo1984 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    String authorName;
Нужно везде проставить модификаторы доступа

2022-08-24 13:17 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private Validation validation;
Исправлено

2022-08-24 13:46 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Везде стоит OrderByStart - то есть по более новым.

2022-08-24 13:47 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Исправлено

2022-08-24 13:54 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
исправлено

2022-08-24 13:54 UTC, grigory-pc commented on src/main/resources/schema.sql
> +);
Это экспорт из dbdiagram.io. Idea приняла в таком формате, я и оставил)

2022-08-24 13:56 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    void deleteBooking(long userId, long bookingId);
исправлено

2022-08-24 13:57 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingOutDto> getBookings(long userId);
Исправлено

2022-08-24 14:00 UTC, grigory-pc commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    String authorName;
Исправлено

2022-08-27 09:41 UTC, merged